using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TransactionsRecordFile.Models
{
    public class TransactionType
    {
        //the primary key field is not an int  by default
        // it will NOT be auto-generated by the DB -
        public string TransactionTypeId { get; set; }

        public string Name { get; set; }

        public double Fee { get; set; }
    }
}
